# Generated by Django 3.0 on 2024-08-15 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('numero_casa', models.PositiveSmallIntegerField(verbose_name='Número da Casa')),
                ('placa_veiculo', models.CharField(blank=True, max_length=7, null=True, verbose_name='Placa do Veículo')),
                ('hora_chegada', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Hora de Chegada')),
                ('hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('hora_autorizacao', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Autorização')),
                ('nome_morador', models.CharField(blank=True, max_length=255, verbose_name='Nome do Morador que autorizou a entrada')),
                ('porteiro_autorizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitantes_autorizados', to='porteiros.Porteiro', verbose_name='Porteiro que Autorizou a Entrada')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
            },
        ),
    ]
