# Generated by Django 3.0 on 2024-08-15 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='porteiro_autorizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porteiros.Porteiro', verbose_name='Porteiro que Autorizou a Entrada'),
        ),
    ]
